import {
  MdDashboard,
  MdLocationOn,
  MdExpandMore,
  MdExpandLess,
  MdEvent,
  MdEventNote,
  MdPayment,
  MdHotel,
  MdPeople,
  MdRocket,
  MdNotifications,
  MdStar,
  MdAdminPanelSettings,
  MdSettings,
  MdList,
  MdCategory,
  MdLocalOffer,
  MdReceipt,
} from "react-icons/md";

export const SIDEBAR_ITEMS = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: MdDashboard,
    path: "/admin/dashboard",
    hasSubItems: false,
  },
  {
    id: "manage-destinations",
    title: "Manage Destinations",
    icon: MdLocationOn,
    hasSubItems: true,
    isExpanded: true,
    subItems: [
      {
        id: "package-list",
        title: "Package List",
        path: "/admin/destinations/packages",
        isDisabled: true,
      },
      {
        id: "category",
        title: "Category",
        path: "/admin/destinations/category",
        isDisabled: false,
      },
      {
        id: "coupon-management",
        title: "Coupon Management",
        path: "/admin/destinations/coupons",
        isDisabled: false,
      },
      {
        id: "transactions",
        title: "Transactions",
        path: "/admin/destinations/transactions",
        isDisabled: false,
      },
    ],
  },
  {
    id: "event-calendar",
    title: "Event Calendar",
    icon: MdEvent,
    path: "/admin/events",
    hasSubItems: false,
  },
  {
    id: "manage-bookings",
    title: "Manage Bookings",
    icon: MdEventNote,
    path: "/admin/bookings",
    hasSubItems: false,
  },
  {
    id: "payment",
    title: "Payment",
    icon: MdPayment,
    path: "/admin/payments",
    hasSubItems: false,
  },
  {
    id: "hotels",
    title: "Hotels",
    icon: MdHotel,
    path: "/admin/hotels",
    hasSubItems: false,
  },
  {
    id: "user-management",
    title: "User Management",
    icon: MdPeople,
    path: "/admin/users",
    hasSubItems: false,
  },
  {
    id: "seo-tools",
    title: "SEO Tools",
    icon: MdRocket,
    hasSubItems: true,
    isExpanded: false,
    subItems: [
      {
        id: "seo-analytics",
        title: "SEO Analytics",
        path: "/admin/seo/analytics",
        isDisabled: false,
      },
      {
        id: "seo-optimization",
        title: "SEO Optimization",
        path: "/admin/seo/optimization",
        isDisabled: false,
      },
      {
        id: "seo-reports",
        title: "SEO Reports",
        path: "/admin/seo/reports",
        isDisabled: false,
      },
    ],
  },
  {
    id: "push-notification",
    title: "Push Notification",
    icon: MdNotifications,
    path: "/admin/notifications",
    hasSubItems: false,
  },
  {
    id: "ratings-reviews",
    title: "Ratings & Reviews",
    icon: MdStar,
    path: "/admin/reviews",
    hasSubItems: false,
  },
];

export const ADMIN_SECTION_ITEMS = [
  {
    id: "admin-profile",
    title: "Admin",
    icon: MdAdminPanelSettings,
    path: "/admin/profile",
    hasSubItems: false,
  },
  {
    id: "settings",
    title: "Settings",
    icon: MdSettings,
    path: "/admin/settings",
    hasSubItems: false,
  },
];
