// app/layout.jsx
import "./globals.css";
import { AuthProvider } from "../contexts/AuthContext";
import QueryProvider from "../providers/QueryProvider";
import { Geist, Geist_Mono, Raleway, Source_Sans_3, Outfit, Mulish } from "next/font/google";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const raleway = Raleway({ variable: "--font-raleway", subsets: ["latin"], weight: ["100","200","300","400","500","600","700","800","900"] });
const sourceSansPro = Source_Sans_3({ variable: "--font-source-sans-pro", subsets: ["latin"], weight: ["300","400","500","600","700"] });
const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"], weight: ["100","200","300","400","500","600","700","800","900"] });
const mulish = Mulish({ variable: "--font-mulish", subsets: ["latin"], weight: ["300","400","500","600","700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${sourceSansPro.variable} ${outfit.variable} ${mulish.variable} antialiased`}>
        <QueryProvider>
          <AuthProvider>{children}</AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
